# Generated by Django 2.2.3 on 2020-02-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20200209_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
    ]
