# Generated by Django 2.2.3 on 2020-01-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='page_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
